version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ezi-db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d

  spring-boot-app:
    image: openjdk:17
    depends_on:
      - postgres
    volumes:
      - ./build/libs/ezi-backend-0.0.1-SNAPSHOT.jar:/app/app.jar
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: ["sh", "-c", "java -jar /app/app.jar"]
    ports:
      - "8080:8080"
