INSERT INTO product (name, price, photo, category_id)
VALUES
    ('Bułka z masłem', 34, pg_read_binary_file('/assets/image.png'), 2),
    ('Ciabatta', 33, pg_read_binary_file('/assets/image.png'), 2),
    ('Brioche', 32, pg_read_binary_file('/assets/image.png'), 2),
    ('Bagietka', 31, pg_read_binary_file('/assets/image.png'), 2),
    ('Pumpernikiel', 30, pg_read_binary_file('/assets/image.png'), 2),
    ('Kaiserk', 43, pg_read_binary_file('/assets/image.png'), 2),
    ('Kiełbasa', 34, pg_read_binary_file('/assets/image.png'), 1),
    ('Szynka', 12, pg_read_binary_file('/assets/image.png'), 1),
    ('Salami', 32, pg_read_binary_file('/assets/image.png'), 1),
    ('Parówki', 326, pg_read_binary_file('/assets/image.png'), 1),
    ('Pasztet', 12, pg_read_binary_file('/assets/image.png'), 1),
    ('Risotto z kurczakiem i warzywami.', 12, pg_read_binary_file('/assets/image.png'), 3),
    ('Spaghetti bolognese z sosem mięsno-pomidorowym.', 21, pg_read_binary_file('/assets/image.png'), 3),
    ('Łosoś z pieczonymi ziemniakami i warzywami.', 174, pg_read_binary_file('/assets/image.png'), 3),
    ('Klasyczne curry z kurczakiem i ryżem basmati.', 322, pg_read_binary_file('/assets/image.png'), 3),
    ('Pieczone piersi z kurczaka z ziołowym sosem.', 87, pg_read_binary_file('/assets/image.png'), 3),
    ('Sacher Torte', 32, pg_read_binary_file('/assets/image.png'), 4),
    ('Tiramisu', 36, pg_read_binary_file('/assets/image.png'), 4),
    ('Szarlotka', 99, pg_read_binary_file('/assets/image.png'), 4),
    ('Brownie', 62, pg_read_binary_file('/assets/image.png'), 4),
    ('Cheesecake', 18, pg_read_binary_file('/assets/image.png'), 4),
    ('Sałatka Cezar', 14, pg_read_binary_file('/assets/image.png'), 5),
    ('Sałatka grecka', 13, pg_read_binary_file('/assets/image.png'), 5),
    ('Sałatka Caprese', 18, pg_read_binary_file('/assets/image.png'), 5),
    ('Sałatka z kurczakiem i awokado', 78, pg_read_binary_file('/assets/image.png'), 5),
    ('Sałatka z quinoa i warzywami', 12, pg_read_binary_file('/assets/image.png'), 5);
